### ISSUE TITLE
Update Courses & Events to show "Past", "Registration Closed", or "Sold Out" when in such a state on the grid, and PDP

### ISSUE THREAD

**Issue by chrismekim** [sanctuarycomputer/nunu#181]
"Hi! I've added Events to the nav and am thinking a little bit about how to make this page more useful. The $0 price seems like unnecessary information — but what would be amazing to include in that space is the date (either past or upcoming) of the event. seems like a long shot? but thought i'd ask in case anyone felt inspired "
- From Elie

Related Twist [thread](https://twist.com/a/133876/ch/376069/t/2477456)
Shopify Bookings [related documentation](https://docs.shopifybookings.com/liquid-rendering/bookable-status)

**Comment by uditdesai** [comment]
Added the states on the grid, but still need to update the PDP with the state and logic concerning the CTA.
